### ISSUE TITLE
What can this be used for? 

### ISSUE THREAD

**Issue by Waterman178** [gcmartinelli/entroPy#1]
What can this be used for? I don't know much about "entropy", can anyone explain?Thanks

**Comment by dougbenham** [comment]
I believe it works something like this.. In a given block, the entropy is defined as the variability of values within that block. So if a block contains all 1 value, it has low entropy. If a block contains an equal number of each value, it has high entropy. So in the visualization the dark areas mean a lot is going on.. And the light areas mean they are very boring and aren't worth looking into.

**Comment by gcmartinelli** [comment]
> What can this be used for? I don't know much about "entropy", can anyone explain?Thanks

Check the video (Red Balloon link) I shared on Readme. It shows how it's used in practice. But TLDR: you can, on a quick glance, have some idea of what a file is composed of (code sections, compressed sections, data, etc).
